"""add hospital

Revision ID: 80eb364b187d
Revises: cb448bd6d636
Create Date: 2024-10-18 22:06:50.302616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80eb364b187d'
down_revision = 'cb448bd6d636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('date_of_visit', sa.Date(), nullable=False))
        batch_op.drop_constraint('patient_record_doctor_id_fkey', type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('patient_record_doctor_id_fkey', 'user', ['doctor_id'], ['id'])
        batch_op.drop_column('date_of_visit')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###
